### ISSUE TITLE
[SUGGESTION] Document CRUD

### ISSUE THREAD

**Issue by kzweb** [orocrm/documentation#124]
Something that is quite common in any system is the CRUD operations. Documenting it would be easier for beginners start Oro.

- Create tables in the database (already exists)
- Create Entities.
- Insert
- Update
- List
- View
- Delete
- Bulk Actions

Or maybe not teach step by step, but provide a simple example.

If there is already this, please send me the link.

Thank you.

**Comment by akuzmenko-magecore** [comment]
Hi @yoocloud,

Just added this section recently
http://www.orocrm.com/documentation/index/current/book/crud
Hope this is what you were looking for.

**Comment by xabbuh** [comment]
@DimaSoroka Is it save to close here as #140 was merged or should it be considered to add some more details?
