### ISSUE TITLE
Wrong relation  for workflowStep in documentation

### ISSUE THREAD

**Issue by yaroslavbr** [orocrm/documentation#217]
https://www.orocrm.com/documentation/index/current/book/workflow#applying-workflows-to-an-entity

 /**
     * @ORM\OneToOne(targetEntity="Oro\Bundle\WorkflowBundle\Entity\WorkflowStep")
     */
    private $workflowStep

I think OneToOne is wrong, in crm other relation is used:

 * @var WorkflowStep
     *
     * @ORM\ManyToOne(targetEntity="Oro\Bundle\WorkflowBundle\Entity\WorkflowStep")

 https://github.com/orocrm/crm/blob/693f6fb8306c07a4914996bb659457246f997ef5/src/OroCRM/Bundle/SalesBundle/Entity/SalesFunnel.php

**Comment by yaroslavbr** [comment]
changes applied

**Comment by sergeyz** [comment]
Fix is in #218
