### ISSUE TITLE
How to Create a Basic Datagrid Errors

### ISSUE THREAD

**Issue by pedroresende** [orocrm/documentation#231]
In the documentation at https://www.orocrm.com/documentation/index/current/cookbook/entities/datagrids mentions that the files should be store at

src/AppBundle/Resources/config/oro/datagrids.yml and
src/AppBundle/Resources/config/oro/navigation.yml

When actually should be

src/AppBundle/Resources/config/datagrid.yml and
src/AppBundle/Resources/config/navigation.yml

datagrids.yml should be datagrid.yml

**Comment by mkudelya** [comment]
Hi @pedroresende 

We will move many config files from Resources/config to Resources/config/oro in the next 2.0 release.

**Comment by pedroresende** [comment]
@mkudelya Ok... however that information should be explicit, for the current versions. Btw, any idea when version 2.0 will be released ?

**Comment by mkudelya** [comment]
We are working on splitting documentation to old and new versions. 2.0 will released at the end of this year.

**Comment by mkudelya** [comment]
Hi @pedroresende 

#232 has been merged. Thank you! I'm closing the issue, Please, feel free to reopen it if you have any questions.
